server:
  port: 8080

spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: stat_service_route
          uri: lb://stats-server
          predicates:
            - Path=/hit/**,/stats/**

        - id: main_service_route
          uri: lb://main-service
          predicates:
            - Path=/admin/**,/users/**,/categories/**,/compilations/**,/events/**