server:
  port: 0

spring:
  sql:
    init:
      mode: always
  datasource:
    driverClassName: org.postgresql.Driver
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5433/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:postgres}
    password: ${SPRING_DATASOURCE_PASSWORD:postgres}
  jpa:
    show-sql: true
    "properties.hibernate.format_sql": true
logging:
  level:
    "org.zalando.logbook": TRACE
    "org.springframework.orm.jpa": INFO
    "org.springframework.orm.jpa.JpaTransactionManager": DEBUG
    "org.springframework.transaction": INFO
    "org.springframework.transaction.interceptor": TRACE